# Generated by Django 4.1.7 on 2023-03-07 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='title',
            field=models.CharField(default='07-03-2023', max_length=100),
        ),
    ]
