# Generated by Django 4.1.7 on 2023-03-10 16:10
from django.db import migrations
from django.conf import settings
from django.db.models import F
from django.db import models
from django.contrib.auth import get_user_model

def set_created_by_default(apps, schema_editor):
    Journal = apps.get_model('home', 'Journal')
    default_user = get_user_model().objects.first()
    Journal.objects.update(created_by=F('created_by') or default_user)

class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_journal_title'),
    ]

    operations = [ migrations.AddField(
            model_name='journal',
            name='created_by',
            field=models.ForeignKey(
                to=settings.AUTH_USER_MODEL,
                null=True,
                blank=True,
                on_delete=models.SET_NULL
            ),
        ),
        migrations.RunPython(set_created_by_default),
        migrations.AlterField(
            model_name='journal',
            name='created_by',
            field=models.ForeignKey(
                to=settings.AUTH_USER_MODEL,
                on_delete=models.CASCADE
            ),
        ),
    ]
