# Generated by Django 4.1.7 on 2023-03-10 16:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.db import migrations
from django.db.models import F
from django.contrib.auth import get_user_model

def set_created_by_default(apps, schema_editor):
    Journal = apps.get_model('home', 'Journal')
    User = get_user_model()

    # Create an anonymous user if one does not exist
    try:
        anonymous_user = User.objects.get(username='anonymous')
    except User.DoesNotExist:
        anonymous_user = User.objects.create_user(
            username='anonymous',
            password='password'
        )

    Journal.objects.update(created_by=F('created_by') or anonymous_user)

class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0004_auto_20230310_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='journal',
            name='title',
            field=models.CharField(default='10-03-2023', max_length=100),
        ),
    ]
