# Generated by Django 4.1.7 on 2023-03-11 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20230310_1718'),
        ('home', '0005_alter_journal_created_by_alter_journal_title'),
    ]

    operations = [
    ]
