# Generated by Django 4.1.7 on 2023-03-11 20:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0006_merge_20230311_2103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='journal',
            name='title',
            field=models.CharField(default='11-03-2023', max_length=100),
        ),
    ]
